export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_CEMETERY = 'SET_CEMETERY'
export const SET_TRANSACTION = 'SET_TRANSACTION'
export const SET_XENDIT = 'SET_XENDIT'